language: python
os: linux
install:
  - pip install -r requirements.dev.txt
  - pip install 'dash[testing]'
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
addons:
  chrome: stable
script:
  - sh download_webdriver.sh
  - pytest --headless  tests/
jobs:
  include:
    - stage: deploy
      deploy:
        provider: pypi
        username: "__token__"
        password: "$PYPI_TOKEN"
        on:
          tags: true